#  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License").
#  You may not use this file except in compliance with the License.
#  A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the "license" file accompanying this file. This file is distributed
#  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
#  express or implied. See the License for the specific language governing
#  permissions and limitations under the License.
# ServiceAccount with RoleBindings required for a single-node and MPI (Horovod) benchmark
# The pods running the actual benchmarks (user-submitted code) are running with this service
# account
# ServiceAccount with RoleBindings required for the executor service to function
apiVersion: v1
kind: ServiceAccount
metadata:
  name: benchmark
---
# Role for observing pod status
# This role is required by the metrics-pusher sidecar
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: benchmark-pod-status-observer-binding
subjects:
- kind: ServiceAccount
  name: benchmark
  namespace: default
roleRef:
  kind: Role
  name: pod-status-observer
  apiGroup: rbac.authorization.k8s.io
---
# Role for observing pod logs
# This role is required by the metrics-extractor
# and metrics-pusher sidecars
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: executor-pod-log-observer-binding
subjects:
- kind: ServiceAccount
  name: benchmark
  namespace: default
roleRef:
  kind: Role
  name: pod-log-observer
  apiGroup: rbac.authorization.k8s.io
---
