#  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License").
#  You may not use this file except in compliance with the License.
#  A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the "license" file accompanying this file. This file is distributed
#  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
#  express or implied. See the License for the specific language governing
#  permissions and limitations under the License.
# ServiceAccount with RoleBindings required for the executor service to function
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-benchmark
---
# Role for observing pod status
# This role is required by the metrics-pusher sidecar
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: inference-benchmark-pod-status-observer-binding
subjects:
- kind: ServiceAccount
  name: inference-benchmark
  namespace: default
roleRef:
  kind: Role
  name: pod-status-observer
  apiGroup: rbac.authorization.k8s.io
---
# This role is required by the job-status-trigger sidecar
# to get the status of the benchmark pod and for the
# job-status-trigger init container to to hold the benchmark pod
# until the inference server is up
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: inference-benchmark-pod-log-observer-binding
subjects:
- kind: ServiceAccount
  name: inference-benchmark
  namespace: default
roleRef:
  kind: Role
  name: pod-log-observer
  apiGroup: rbac.authorization.k8s.io
---
# This role is required by the job-status-trigger sidecar
# to get the status of the benchmark pod and for the
# job-status-trigger init container to to hold the benchmark pod
# until the inference server is up
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: inference-benchmark-job-status-observer-binding
subjects:
- kind: ServiceAccount
  name: inference-benchmark
  namespace: default
roleRef:
  kind: Role
  name: job-status-observer
  apiGroup: rbac.authorization.k8s.io
---
# This role is required by the job-status-trigger sidecar
# to get the status of the benchmark pod and for the
# job-status-trigger init container to to hold the benchmark pod
# until the inference server is up
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: inference-benchmark-inference-benchmark-janitor-binding
subjects:
- kind: ServiceAccount
  name: inference-benchmark
  namespace: default
roleRef:
  kind: Role
  name: inference-benchmark-janitor
  apiGroup: rbac.authorization.k8s.io
---
# This role is required by the job-status-trigger sidecar
# to get the status of the benchmark pod and for the
# job-status-trigger init container to to hold the benchmark pod
# until the inference server is up
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: inference-benchmark-pod-lister-binding
subjects:
- kind: ServiceAccount
  name: inference-benchmark
  namespace: default
roleRef:
  kind: Role
  name: pod-lister
  apiGroup: rbac.authorization.k8s.io
---
