#  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License").
#  You may not use this file except in compliance with the License.
#  A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the "license" file accompanying this file. This file is distributed
#  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
#  express or implied. See the License for the specific language governing
#  permissions and limitations under the License.
# ServiceAccount with RoleBindings required for a scheduled-benchmark service to function
# This is the service account attached to the pod created the CronJob that represents
# the scheduled benchmark. Since all it does it emit an event to a kafka topic, it needs
# no special kubernetes resource access.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduled-benchmark
---