apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint
  namespace: default
  benchmark: {job_id}
data:
  entrypoint: |-
    {container_args}

  init_entrypoint.sh: |-
    #!/bin/bash
    if [ "$ROLE" == "worker" ]; then
      /opt/behance/download-s3-files "$@"
    else
      echo "Not a worker - no data necessary"
    fi  
---

apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: {job_id}
  labels:
    app: benchmark-ai
spec:
  replicas: {num_instances}
  template:
    spec:
      initContainers:
      - name: data-puller
        command: 
        - /bin/init_entrypoint.sh
      #   image: stsukrov/s3dataprovider
      #   args:
      #     - "eu-west-1"
      #     - "mlperf-data-temp"
      #     - imagenet/validation-480px,777,/data/p1:imagenet/train-480px,777,/data/p1
        volumeMounts:
        # - mountPath: /data/p1
        #   name: p1
        - name: entrypoint
          mountPath: /bin/init_entrypoint.sh
          readOnly: true
          subPath: init_entrypoint.sh
        env:
        - name: ROLE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['mpi_role_type']
      containers:
      - image: {docker_image}
        name: benchmark
        command: 
        - /bin/entrypoint.sh
        volumeMounts:
        # - mountPath: /root/data/tf-imagenet
        #   name: p1
        - name: entrypoint
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
        # - mountPath: /dev/shm
        #   name: dshm
        # resources:
        #   limits:
        #     nvidia.com/gpu: 1
      volumes:
      #Hack to iterate faster
      # - name: p1
      #   hostPath:
      #     path: /mldata
      #     type: DirectoryOrCreate
      - name: entrypoint
        configMap:
          defaultMode: 0700
          name: entrypoint
      # #Shared memory trick
      # - name: dshm
      #   emptyDir:
      #     medium: Memory
      nodeSelector:
        beta.kubernetes.io/instance-type: {instance_type}