#  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License").
#  You may not use this file except in compliance with the License.
#  A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the "license" file accompanying this file. This file is distributed
#  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
#  express or implied. See the License for the specific language governing
#  permissions and limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudwatch-exporter
  labels:
    app: benchmark-ai
spec:
  selector:
    matchLabels:
      app: benchmark-ai
  replicas: 1
  template:
    metadata:
      labels:
        app: benchmark-ai
        service: cloudwatch-exporter
      annotations:
        iam.amazonaws.com/role: cloudwatch-exporter
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: service
                    operator: In
                    values:
                      - cloudwatch-exporter
              topologyKey: kubernetes.io/hostname
      containers:
        - name: cloudwatch-exporter
          image: "benchmarkai/cloudwatch-exporter"
          imagePullPolicy: Always
          env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: outputs-infrastructure
                key: msk_bootstrap_brokers
          - name: CONSUMER_GROUP_ID
            valueFrom:
               configMapKeyRef:
                 name: cloudwatch-exporter
                 key: consumer_group_id
          - name: CONSUMER_TOPIC
            valueFrom:
              configMapKeyRef:
                name: cloudwatch-exporter
                key: consumer_topic
          - name: PRODUCER_TOPIC
            valueFrom:
              configMapKeyRef:
                name: cloudwatch-exporter
                key: producer_topic
          - name: STATUS_TOPIC
            valueFrom:
              configMapKeyRef:
                name: cloudwatch-exporter
                key: status_topic
          - name: LOGGING_LEVEL
            value: "INFO"
          - name: AWS_DEFAULT_REGION
            valueFrom:
              configMapKeyRef:
                key: region
                name: outputs-infrastructure
      nodeSelector:
        node.type: bai-services-cheap
      restartPolicy: Always
