name: watcher
channels:
  - conda-forge
  - defaults
dependencies:
  - python 3.7.*
  - kazoo 2.5.*
  - boto3 1.9.*
  - python-kubernetes 9.0.*
  - pycurl 7.43.*
  - pip
  - pip:
      - dataclasses-json
      - ConfigArgParse
      - dacite
      # Installing kafka-python from github because there is a bug with topic creation which is only fixed on master
      # https://github.com/dpkp/kafka-python/issues/1657#issuecomment-463290906
      - git+git://github.com/dpkp/kafka-python.git@f126e5bfcc8f41ee5ea29b41ec6eabbc3f441647
