apiVersion: batch/v1
kind: Job
metadata:
  name: mxnet
spec:
  template:
    spec:
      containers:
      - name: mxnetpyth
        image: mxnet/python:1.3.1_cpu_py3
        command: ["python3"]
        args: ["-c", "print('hello')"]
      nodeSelector:
        beta.kubernetes.io/instance-type: t3.small
      restartPolicy: Never
  backoffLimit: 4
