apiVersion: batch/v1
kind: Job
metadata:
  name: mxnet
spec:
  template:
    metadata:
      labels:
        app: benchmark-ai
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - benchmark-ai
            topologyKey: kubernetes.io/hostname
      containers:
      - name: name
        image: image
        command: ["/bin/sh", "-c"]
        args:
          - cmd 1; cmd 2;
      nodeSelector:
        beta.kubernetes.io/instance-type: instance-type
      restartPolicy: Never
  backoffLimit: 4
