name: kafka-utils-test
channels:
  - conda-forge
  - defaults
dependencies:
  - kazoo 2.5.*
  - pip
  - pip:
      - ConfigArgParse
      - dataclasses-json
      - dacite
      # Installing kafka-python from github because there is a bug with topic creation which is only fixed on master
      # https://github.com/dpkp/kafka-python/issues/1657#issuecomment-463290906
      - git+git://github.com/dpkp/kafka-python.git@f126e5bfcc8f41ee5ea29b41ec6eabbc3f441647
