#  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License").
#  You may not use this file except in compliance with the License.
#  A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the "license" file accompanying this file. This file is distributed
#  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
#  express or implied. See the License for the specific language governing
#  permissions and limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-kafka-topic-exporter
  labels:
    app: benchmark-ai
spec:
  selector:
    matchLabels:
      app: benchmark-ai
  replicas: 1
  template:
    metadata:
      labels:
        app: benchmark-ai
        service: prometheus-kafka-topic-exporter
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: service
                    operator: In
                    values:
                      - prometheus-kafka-topic-exporter
              topologyKey: kubernetes.io/hostname
      containers:
        - name: prometheus-kafka-topic-exporter
          imagePullPolicy: Always
          image: @@DOCKER_IMAGE_TAG@@
          env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: outputs-infrastructure
                key: msk_bootstrap_brokers
          - name: KAFKA_ZOOKEEPER_SERVERS
            valueFrom:
              configMapKeyRef:
                name: outputs-infrastructure
                key: msk_zookeeper_connect
          - name: METRICS_CONSUMER_TOPIC
            value: "BAI_METRICS"
          - name: KAFKA_REPLICATION_FACTOR
            value: "3"
          - name: KAFKA_PARTITIONS
            value: "3"
          volumeMounts:
            - mountPath: /config
              name: config-volume
      nodeSelector:
        node.type: bai-services-cheap
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-kafka-topic-exporter-config
