apiVersion: batch/v1
kind: Job
metadata:
  name: mxnet
spec:
  template:
    metadata:
      labels:
        app: benchmark-ai
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - benchmark-ai
            topologyKey: kubernetes.io/hostname
      containers:
      - name: mxnetpyth
        image: mxnet/python:1.3.1_cpu_py3
        command: ["/bin/sh", "-c"]
        args:
          - echo "Downloading data";
            python download_data_script.py dataset;
            echo "Running benchmark";
            python benchmark_code.py arg1 arg2;
      nodeSelector:
        beta.kubernetes.io/instance-type: t3.small
      restartPolicy: Never
  backoffLimit: 4