#  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License").
#  You may not use this file except in compliance with the License.
#  A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the "license" file accompanying this file. This file is distributed
#  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
#  express or implied. See the License for the specific language governing
#  permissions and limitations under the License.
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-utils-it
spec:
  template:
    spec:
      #serviceAccountName: fetcher-dispatcher
      containers:
        - name: it
          image: benchmarkai/kafka-utils-it
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: outputs-infrastructure
                  key: msk_bootstrap_brokers
            - name: ZOOKEEPER_ENSEMBLE_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: zookeeper
                  key: connect
            - name: CONSUMER_GROUP_ID
              value: kafka-utils-test
            - name: PYTEST_ARGS
              value: "-o log_cli=true --log-cli-level=INFO"
      restartPolicy: Never
  backoffLimit: 0
