#  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License").
#  You may not use this file except in compliance with the License.
#  A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the "license" file accompanying this file. This file is distributed
#  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
#  express or implied. See the License for the specific language governing
#  permissions and limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
  labels:
    app: benchmark-ai
spec:
  selector:
    matchLabels:
      app: benchmark-ai
  replicas: 1
  template:
    metadata:
      labels:
        app: benchmark-ai
        service: watcher
      annotations:
        # TODO: Make a special role for the watcher with only "job describe" authorization
        iam.amazonaws.com/role: sagemaker-executor-role
    spec:
      serviceAccountName: watcher
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: service
                    operator: In
                    values:
                      - watcher
              topologyKey: kubernetes.io/hostname
      containers:
        - name: watcher
          image: @@DOCKER_IMAGE_TAG@@
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: outputs-infrastructure
                  key: msk_bootstrap_brokers
            - name: CONSUMER_GROUP_ID
              value: watcher
            - name: CONSUMER_TOPIC
              value: BAI_APP_EXECUTOR
            - name: PRODUCER_TOPIC
              value: BAI_APP_FETCHER
            - name: STATUS_TOPIC
              value: BAI_APP_STATUS
            - name: LOGGING_LEVEL
              value: INFO
            - name: SERVICE_LOGGING_LEVEL
              value: DEBUG
            - name: GRAFANA_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: grafana
                  key: grafana_endpoint
            - name: GRAFANA_OP_METRICS_DASHBOARD_UID
              valueFrom:
                configMapKeyRef:
                  name: grafana
                  key: op_metrics_dashboard_uid
            - name: GRAFANA_RESULTS_URL
              valueFrom:
                configMapKeyRef:
                  name: watcher
                  key: grafana_results_url
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  key: region
                  name: outputs-infrastructure
      nodeSelector:
        node.type: bai-services-cheap
      restartPolicy: Always
