#  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License").
#  You may not use this file except in compliance with the License.
#  A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the "license" file accompanying this file. This file is distributed
#  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
#  express or implied. See the License for the specific language governing
#  permissions and limitations under the License.
# ServiceAccount with RoleBindings required for the executor service to function
apiVersion: v1
kind: ServiceAccount
metadata:
  name: executor-it
---
# This role defines all the required permissions for the
# integration test pod
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: integration-tester
  namespace: default
rules:
- apiGroups: ["batch"]
  resources: ["jobs/status"]
  verbs: ["get"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods", "services", "pods/status", "pods/logs"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: executor-it-integration-tester-binding
subjects:
- kind: ServiceAccount
  name: executor-it
  namespace: default
roleRef:
  kind: Role
  name: integration-tester
  apiGroup: rbac.authorization.k8s.io

