#  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License").
#  You may not use this file except in compliance with the License.
#  A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the "license" file accompanying this file. This file is distributed
#  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
#  express or implied. See the License for the specific language governing
#  permissions and limitations under the License.
# Example service account, role, and role binding
# with minimal required authorizations
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: inference-benchmark
  namespace: default
rules:
- apiGroups: ["batch"]
  resources: ["jobs/status"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["", "batch"]
  resources: ["jobs", "pods", "services"]
  verbs: ["delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: inference-benchamrk-role-binding
subjects:
- kind: ServiceAccount
  name: metrics-pusher
  namespace: default
roleRef:
  kind: Role
  name: inference-benchmark
  apiGroup: rbac.authorization.k8s.io
